public: true
type: "docs"
category: "preservation"
tags:
  - "digital preservation"
  - "rights"
title: "Guidelines for PREMIS Rights Statements at the Rockefeller Archive Center"
description: "Local guidelines for the content of PREMIS rights statements."
pages:
  - ["Guidelines for PREMIS Rights Statements at the Rockefeller Archive Center", "index"]
