public: true
type: "docs"
category: "preservation"
tags:
  - "digital preservation"
  - "rights"
title: "Guidelines for PREMIS Rights Statements"
description: "Local guidelines for the content of PREMIS rights statements."
pages:
  - ["Introduction", "index"]
  - ["Guidelines", "guidelines"]
  
